const state = { venues: [], filtered: [], page: 40, filter: 'restaurant', map: null, selected: null };
let supabaseClient = null;
const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char]));
const accountList = () => JSON.parse(localStorage.getItem('halal-accounts') || '[]');
const currentAccount = () => JSON.parse(localStorage.getItem('halal-current') || 'null');
const favoriteIds = () => JSON.parse(localStorage.getItem('halal-favorites') || '[]');
const categoryName = (venue) => ({ restaurant: 'ร้านอาหาร', cafe: 'คาเฟ่', fast_food: 'อาหารจานด่วน', place_of_worship: 'สถานที่ประกอบศาสนกิจ', tourism: 'สถานที่ท่องเที่ยว', attraction: 'สถานที่ท่องเที่ยว', viewpoint: 'จุดชมวิว' }[venue.category] || 'สถานที่');
const icon = (venue) => venue.category === 'place_of_worship' ? '🕌' : ['tourism', 'attraction', 'viewpoint'].includes(venue.category) ? '⛰️' : '🍽️';
const badge = (venue) => venue.halalStatus === 'certified' ? '<span class="badge certified">✓ Halal Certified</span>' : venue.halalStatus === 'muslim_friendly' ? '<span class="badge friendly">✦ Muslim-Friendly</span>' : '<span class="badge unverified">! Unverified</span>';
const media = (venue) => venue.image ? `<img src="${escapeHtml(venue.image)}" alt="รูป ${escapeHtml(venue.name)}" loading="lazy">` : `<span>${icon(venue)}</span>`;
function toast(message) { const element = $('#toast'); element.textContent = message; element.classList.add('show'); clearTimeout(window.toastTimer); window.toastTimer = setTimeout(() => element.classList.remove('show'), 2500); }
function showView(name) { $$('.screen').forEach((screen) => screen.classList.toggle('active', screen.id === `${name}Screen`)); $$('.nav button').forEach((button) => button.classList.toggle('active', button.dataset.view === name)); window.scrollTo(0, 0); if (name === 'map') setTimeout(renderMap, 80); if (name === 'favorites') renderFavorites(); if (name === 'account') renderAccount(); }
function venueCard(venue) { const saved = favoriteIds().includes(venue.id); return `<article class="venue" data-id="${escapeHtml(venue.id)}"><div class="venue-thumb">${media(venue)}</div><div class="venue-body"><div>${badge(venue)}</div><h2>${escapeHtml(venue.name || 'ไม่ระบุชื่อสถานที่')}</h2><span class="meta">${categoryName(venue)}${venue.address ? ` · ${escapeHtml(venue.address)}` : ''}</span>${venue.cuisine ? `<span class="meta">${escapeHtml(venue.cuisine)}</span>` : ''}</div><button class="heart ${saved ? 'saved' : ''}" data-fav="${escapeHtml(venue.id)}">${saved ? '♥' : '♡'}</button></article>`; }
function bindCards(container = document) { container.querySelectorAll('[data-id]').forEach((element) => element.onclick = (event) => { if (!event.target.closest('[data-fav]')) openDetail(element.dataset.id); }); container.querySelectorAll('[data-fav]').forEach((button) => button.onclick = (event) => { event.stopPropagation(); toggleFavorite(button.dataset.fav); }); }
function renderResults() { const visible = state.filtered.slice(0, state.page); const labels = { restaurant: 'ร้านอาหารใกล้คุณ', cafe: 'คาเฟ่ในเชียงราย', place_of_worship: 'มัสยิดและที่ละหมาด', tourism: 'สถานที่ท่องเที่ยว', all: 'สถานที่ในเชียงราย' }; $('.section-title h1').textContent = labels[state.filter] || labels.all; $('#resultCount').textContent = `${state.filtered.length.toLocaleString('th-TH')} รายการ`; $('#results').innerHTML = visible.length ? visible.map(venueCard).join('') : '<div class="empty">ไม่พบสถานที่ตามคำค้น</div>'; $('#loadMore').style.display = state.page < state.filtered.length ? 'block' : 'none'; bindCards($('#results')); }
function applyFilter() { const query = $('#search').value.trim().toLocaleLowerCase('th-TH'); state.filtered = state.venues.filter((venue) => { const matchesFilter = state.filter === 'all' || venue.category === state.filter || (state.filter === 'restaurant' && ['restaurant', 'fast_food'].includes(venue.category)); const text = `${venue.name || ''} ${venue.address || ''} ${venue.cuisine || ''}`.toLocaleLowerCase('th-TH'); return matchesFilter && text.includes(query); }); state.page = 40; renderResults(); }
async function loadVenues() { try { const response = await fetch('/api/venues'); if (!response.ok) throw Error(); state.venues = (await response.json()).data; } catch { state.venues = await (await fetch('/data/venues.json')).json(); } applyFilter(); }
function openDetail(id) { const venue = state.venues.find((item) => item.id === id); if (!venue) return; state.selected = venue; const location = venue.latitude && venue.longitude ? '<button class="secondary small" id="showOnMap">ดูบนแผนที่</button>' : ''; $('#detail').innerHTML = `<div class="detail-hero">${media(venue)}</div><div>${badge(venue)}<h2>${escapeHtml(venue.name || 'ไม่ระบุชื่อสถานที่')}</h2><p><b>${categoryName(venue)}</b>${venue.address ? ` · ${escapeHtml(venue.address)}` : ''}</p><p>${escapeHtml(venue.verificationNote || 'ข้อมูลจาก OpenStreetMap และยังรอการตรวจสอบ')}</p><div class="actions">${location}<button class="primary" id="route">นำทางในแอพ</button></div><section class="detail-block"><h3>ข้อมูลสถานที่</h3>${venue.cuisine ? `<div class="detail-row"><span>ประเภท</span><span>${escapeHtml(venue.cuisine)}</span></div>` : ''}${venue.phone ? `<div class="detail-row"><span>โทรศัพท์</span><span>${escapeHtml(venue.phone)}</span></div>` : ''}${venue.website ? `<div class="detail-row"><span>เว็บไซต์</span><span>${escapeHtml(venue.website)}</span></div>` : ''}<div class="detail-row"><span>แหล่งข้อมูล</span><span>OpenStreetMap</span></div></section><div class="warning">สถานะฮาลาลของรายการนี้ยังไม่ได้รับรองจากผู้ดูแลระบบ ห้ามใช้รายการนี้แทนใบรับรองฮาลาล</div></div>`; $('#route').onclick = () => openRoute(venue); $('#showOnMap')?.addEventListener('click', () => showRoute(venue, false)); $('#reportButton').onclick = () => report(venue); showView('detail'); }
function openRoute(venue) { if (!venue.latitude || !venue.longitude) return toast('สถานที่นี้ไม่มีพิกัดสำหรับนำทาง'); showRoute(venue, true); }
async function showRoute(venue, requestLocation) { showView('map'); state.selected = venue; $('#routePanel').innerHTML = `<b>กำลังคำนวณเส้นทางไป ${escapeHtml(venue.name)}</b><span>ใช้ OSRM แบบไม่ต้องใช้ API key</span>`; let origin = [19.9072, 99.8309]; if (requestLocation && navigator.geolocation) { try { const position = await new Promise((resolve, reject) => navigator.geolocation.getCurrentPosition(resolve, reject, { enableHighAccuracy: true, timeout: 7000 })); origin = [position.coords.latitude, position.coords.longitude]; } catch { toast('ไม่ได้รับพิกัด ใช้ใจกลางเชียงรายเป็นจุดเริ่มต้น'); } } renderMap(); if (!state.map) return; state.map.setView(origin, 13); try { const url = `https://router.project-osrm.org/route/v1/driving/${origin[1]},${origin[0]};${venue.longitude},${venue.latitude}?overview=full&geometries=geojson&steps=true`; const response = await fetch(url); if (!response.ok) throw Error(); const route = (await response.json()).routes?.[0]; if (!route) throw Error(); if (state.routeLine) state.map.removeLayer(state.routeLine); state.routeLine = L.geoJSON(route.geometry, { style: { color: '#047857', weight: 6, opacity: .85 } }).addTo(state.map); state.map.fitBounds(state.routeLine.getBounds(), { padding: [24, 24] }); const minutes = Math.max(1, Math.round(route.duration / 60)); const km = (route.distance / 1000).toFixed(1); $('#routePanel').innerHTML = `<b>เส้นทางไป ${escapeHtml(venue.name)}</b><strong>${km} กม. · ประมาณ ${minutes} นาที</strong><span>เส้นทางแสดงอยู่บนแผนที่ในแอพนี้</span>`; } catch { $('#routePanel').innerHTML = `<b>ปักหมุด ${escapeHtml(venue.name)} แล้ว</b><span>บริการคำนวณเส้นทางไม่ตอบสนอง แต่ตำแหน่งปลายทางแสดงบนแผนที่แล้ว</span>`; toast('คำนวณเส้นทางไม่ได้ชั่วคราว'); } }
function renderMap() { if (typeof L === 'undefined') return toast('โหลดไลบรารีแผนที่ไม่สำเร็จ'); if (state.map) state.map.remove(); state.map = L.map('map', { preferCanvas: true }).setView([19.9072, 99.8309], 10); L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png', { maxZoom: 20, subdomains: 'abcd', attribution: '© OpenStreetMap © CARTO' }).addTo(state.map); const filter = $('.map-tools .selected')?.dataset.mapFilter || 'food'; const places = state.venues.filter((venue) => venue.latitude && venue.longitude).filter((venue) => filter === 'all' || (filter === 'worship' ? venue.category === 'place_of_worship' : ['restaurant', 'cafe', 'fast_food'].includes(venue.category))); const clusters = typeof L.markerClusterGroup === 'function' ? L.markerClusterGroup({ showCoverageOnHover: false, maxClusterRadius: 46, disableClusteringAtZoom: 15, spiderfyOnMaxZoom: true }) : L.layerGroup(); places.forEach((venue) => { const marker = L.marker([venue.latitude, venue.longitude], { title: venue.name || 'สถานที่' }); marker.bindPopup(`<b>${escapeHtml(venue.name || 'สถานที่')}</b><br>${categoryName(venue)}<br><div class="popup-actions"><button class="map-route" data-route-id="${escapeHtml(venue.id)}">นำทางในแอพ</button><button class="map-favorite" data-map-fav="${escapeHtml(venue.id)}">${favoriteIds().includes(venue.id) ? '♥ บันทึกแล้ว' : '♡ บันทึก'}</button></div>`); clusters.addLayer(marker); }); clusters.addTo(state.map); state.map.invalidateSize(); }
function renderFavorites() { const list = state.venues.filter((venue) => favoriteIds().includes(venue.id)); $('#favorites').innerHTML = currentAccount() ? list.length ? `<div class="results">${list.map(venueCard).join('')}</div>` : '<div class="empty">ยังไม่มีรายการโปรด<br>กดหัวใจบนสถานที่ที่ต้องการบันทึก</div>' : '<div class="empty"><h2>เข้าสู่ระบบก่อน</h2><p>สร้างบัญชีเพื่อบันทึกร้านและซิงค์รายการโปรด</p><button class="primary" id="favoriteLogin">สมัครสมาชิก / เข้าสู่ระบบ</button></div>'; $('#favoriteLogin')?.addEventListener('click', () => openAuth('register')); bindCards($('#favorites')); }
function toggleFavorite(id) { if (!currentAccount()) return openAuth('register', () => toggleFavorite(id)); const list = favoriteIds(); localStorage.setItem('halal-favorites', JSON.stringify(list.includes(id) ? list.filter((item) => item !== id) : [...list, id])); toast(list.includes(id) ? 'ลบออกจากรายการโปรดแล้ว' : 'บันทึกรายการโปรดแล้ว'); renderResults(); renderFavorites(); }
async function hash(value) { if (crypto?.subtle) { const buffer = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value)); return [...new Uint8Array(buffer)].map((item) => item.toString(16).padStart(2, '0')).join(''); } return btoa(value); }
function openAuth(mode = 'register', after) { modal(`<h2>${mode === 'register' ? 'สร้างบัญชีใหม่' : 'เข้าสู่ระบบ'}</h2><p>บัญชีนี้ใช้สำหรับรายการโปรดและการรีวิว</p><form id="authForm"><label class="field">อีเมล<input type="email" name="email" required autocomplete="email"></label><label class="field">รหัสผ่าน<input type="password" name="password" required minlength="8" autocomplete="${mode === 'register' ? 'new-password' : 'current-password'}"></label>${mode === 'register' ? '<label class="check"><input type="checkbox" name="consent" required> ฉันยินยอม Privacy Policy และการจัดเก็บข้อมูลบัญชี</label>' : ''}<div class="modal-actions"><button type="button" class="secondary" data-close>ยกเลิก</button><button class="primary">${mode === 'register' ? 'สมัครสมาชิก' : 'เข้าสู่ระบบ'}</button></div></form><button class="secondary full" id="switchAuth">${mode === 'register' ? 'มีบัญชีแล้ว? เข้าสู่ระบบ' : 'ยังไม่มีบัญชี? สมัครสมาชิก'}</button>`); $('#switchAuth').onclick = () => openAuth(mode === 'register' ? 'login' : 'register', after); $('#authForm').onsubmit = (event) => submitAuth(event, mode, after); }
async function submitAuth(event, mode, after) { event.preventDefault(); const form = new FormData(event.currentTarget); const email = String(form.get('email')).toLowerCase(); const passwordHash = await hash(String(form.get('password'))); const all = accountList(); if (mode === 'register') { if (!form.get('consent')) return; if (all.some((account) => account.email === email)) return toast('อีเมลนี้มีบัญชีแล้ว'); all.push({ email, passwordHash, createdAt: new Date().toISOString(), consentAt: new Date().toISOString() }); localStorage.setItem('halal-accounts', JSON.stringify(all)); } else if (!all.some((account) => account.email === email && account.passwordHash === passwordHash)) return toast('อีเมลหรือรหัสผ่านไม่ถูกต้อง'); localStorage.setItem('halal-current', JSON.stringify({ email })); closeModal(); toast(mode === 'register' ? 'สร้างบัญชีสำเร็จ' : 'เข้าสู่ระบบสำเร็จ'); after?.(); renderAccount(); }
function renderAccount() { const account = currentAccount(); $('#accountContent').innerHTML = account ? `<div class="account-card"><h2>${escapeHtml(account.email)}</h2><p>บัญชีผู้ใช้พร้อมบันทึกรายการโปรด</p><button class="secondary full" id="logout">ออกจากระบบ</button></div>` : '<div class="account-card"><h2>Guest Mode</h2><p>เรียกดูข้อมูลได้โดยไม่สมัครสมาชิก แต่ต้องมีบัญชีเพื่อบันทึกรายการโปรด</p><button class="primary full" id="register">สร้างบัญชี</button><button class="secondary full" id="login">เข้าสู่ระบบ</button></div>'; $('#register')?.addEventListener('click', () => openAuth('register')); $('#login')?.addEventListener('click', () => openAuth('login')); $('#logout')?.addEventListener('click', () => { localStorage.removeItem('halal-current'); toast('ออกจากระบบแล้ว'); renderAccount(); renderFavorites(); }); }
function report(venue) { modal(`<h2>รายงานข้อมูล</h2><p>${escapeHtml(venue.name)}</p><form id="reportForm"><label class="field">เหตุผล<select name="reason"><option>ข้อมูลผิดหรือไม่อัปเดต</option><option>สถานที่ปิดแล้ว</option><option>สถานะฮาลาลไม่ถูกต้อง</option></select></label><label class="field">รายละเอียด<textarea name="detail" rows="4"></textarea></label><button class="primary full">ส่งรายงาน</button></form>`); $('#reportForm').onsubmit = (event) => { event.preventDefault(); const reports = JSON.parse(localStorage.getItem('halal-reports') || '[]'); reports.push({ venueId: venue.id, at: new Date().toISOString(), ...Object.fromEntries(new FormData(event.currentTarget)) }); localStorage.setItem('halal-reports', JSON.stringify(reports)); closeModal(); toast('ส่งรายงานให้ผู้ดูแลแล้ว'); }; }
function modal(content) { $('#modal').innerHTML = content; $('#backdrop').classList.add('open'); $$('[data-close]').forEach((button) => button.onclick = closeModal); }
function closeModal() { $('#backdrop').classList.remove('open'); }
document.addEventListener('click', (event) => { const view = event.target.closest('[data-view]')?.dataset.view; if (view) showView(view); const routeId = event.target.closest('[data-route-id]')?.dataset.routeId; if (routeId) { const venue = state.venues.find((item) => item.id === routeId); if (venue) showRoute(venue, true); } const mapFavorite = event.target.closest('[data-map-fav]')?.dataset.mapFav; if (mapFavorite) { toggleFavorite(mapFavorite); state.map?.closePopup(); } });
$('#search').oninput = applyFilter; $('#loadMore').onclick = () => { state.page += 40; renderResults(); }; $$('[data-filter]').forEach((button) => button.onclick = () => { $$('[data-filter]').forEach((item) => item.classList.remove('active')); button.classList.add('active'); state.filter = button.dataset.filter; applyFilter(); }); $$('[data-map-filter]').forEach((button) => button.onclick = () => { $$('[data-map-filter]').forEach((item) => item.classList.remove('selected')); button.classList.add('selected'); renderMap(); }); $('#allowLocation').onclick = () => navigator.geolocation?.getCurrentPosition((position) => { localStorage.setItem('halal-location-consent', new Date().toISOString()); $('#locationNotice').remove(); toast(`พบตำแหน่งแล้ว (${position.coords.latitude.toFixed(3)}, ${position.coords.longitude.toFixed(3)})`); }, () => toast('ไม่อนุญาตตำแหน่ง ใช้การค้นหาด้วยพื้นที่แทน')); $('#locateMe').onclick = () => navigator.geolocation?.getCurrentPosition((position) => state.map?.setView([position.coords.latitude, position.coords.longitude], 14), () => toast('ไม่สามารถอ่านตำแหน่งได้'));
async function initializeSupabase() {
	if (!window.supabase) return;
	try {
		const response = await fetch('/api/config');
		const config = await response.json();
		if (config.supabaseUrl && config.supabasePublishableKey) supabaseClient = window.supabase.createClient(config.supabaseUrl, config.supabasePublishableKey);
	} catch { supabaseClient = null; }
}

const localSubmitAuth = submitAuth;
submitAuth = async (event, mode, after) => {
	if (!supabaseClient) return localSubmitAuth(event, mode, after);
	event.preventDefault();
	const form = new FormData(event.currentTarget);
	const email = String(form.get('email')).toLowerCase();
	const password = String(form.get('password'));
	if (mode === 'register' && !form.get('consent')) return;
	const result = mode === 'register'
		? await supabaseClient.auth.signUp({ email, password })
		: await supabaseClient.auth.signInWithPassword({ email, password });
	if (result.error) return toast(result.error.message || 'ไม่สามารถยืนยันบัญชีได้');
	localStorage.setItem('halal-current', JSON.stringify({ email }));
	closeModal();
	toast(mode === 'register' ? 'สร้างบัญชี Supabase สำเร็จ กรุณายืนยันอีเมลหากระบบร้องขอ' : 'เข้าสู่ระบบสำเร็จ');
	after?.();
	renderAccount();
};

initializeSupabase();
loadVenues().catch(() => toast('โหลดข้อมูลไม่สำเร็จ'));
renderAccount();