import { useEffect, useRef, useState } from 'react';
import L from 'leaflet';
import 'leaflet.markercluster';
import { categoryName, favoriteIds, mapsSearchUrl } from '../../utils/storage.js';
import { hasCoordinates, isMuslimRelated } from '../../services/venueFilters.js';
import styles from './MapPage.module.css';

const center = [19.9072, 99.8309];
const cartoApiKey = import.meta.env.VITE_CARTO_API_KEY;
const cartoTiles = `https://{s}.basemaps.cartocdn.com/voyager/{z}/{x}/{y}.png?key=${encodeURIComponent(cartoApiKey || '')}`;
const escapeHtml = (value) => String(value || '').replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character]));

export default function MapPage({ venues, onBack, onLocate, onRoute, selected, onFavorite, onToast, route }) {
  const mapNode = useRef(null); const mapRef = useRef(null); const clusterRef = useRef(null); const routeRef = useRef(null); const [filter, setFilter] = useState('food');
  useEffect(() => { if (!mapNode.current || mapRef.current) return undefined; mapRef.current = L.map(mapNode.current, { preferCanvas: true }).setView(center, 10); L.tileLayer(cartoTiles, { maxZoom: 20, subdomains: 'abcd', attribution: '© OpenStreetMap © CARTO' }).addTo(mapRef.current); return () => { mapRef.current?.remove(); mapRef.current = null; }; }, []);
  useEffect(() => { const map = mapRef.current; if (!map) return; if (clusterRef.current) map.removeLayer(clusterRef.current); const places = venues.filter(hasCoordinates).filter((venue) => filter === 'all' ? isMuslimRelated(venue) : filter === 'worship' ? venue.category === 'place_of_worship' && isMuslimRelated(venue) : ['restaurant', 'cafe', 'fast_food'].includes(venue.category) && isMuslimRelated(venue)); const clusters = L.markerClusterGroup({ showCoverageOnHover: false, maxClusterRadius: 46, disableClusteringAtZoom: 15, spiderfyOnMaxZoom: true }); places.forEach((venue) => { const marker = L.marker([Number(venue.latitude), Number(venue.longitude)], { title: venue.name }); const image = venue.image ? `<img class="map-popup-image" src="${escapeHtml(venue.image)}" alt="รูป ${escapeHtml(venue.name)}">` : ''; marker.bindPopup(`<div class="map-popup">${image}<b>${escapeHtml(venue.name)}</b><small>${escapeHtml(categoryName(venue))}</small><div class="map-popup-actions"><button class="map-route" data-route-id="${escapeHtml(venue.id)}">นำทาง</button><button class="map-favorite" data-map-fav="${escapeHtml(venue.id)}">${favoriteIds().includes(venue.id) ? '♥ บันทึกแล้ว' : '♡ บันทึก'}</button></div></div>`); marker.on('popupopen', () => { const route = document.querySelector(`[data-route-id="${venue.id}"]`); const favorite = document.querySelector(`[data-map-fav="${venue.id}"]`); route?.addEventListener('click', () => onRoute(venue)); favorite?.addEventListener('click', () => onFavorite(venue.id)); }); clusters.addLayer(marker); }); clusterRef.current = clusters.addTo(map); map.invalidateSize(); }, [venues, filter, onFavorite, onRoute]);
  useEffect(() => { if (!selected || !hasCoordinates(selected) || !mapRef.current) return; mapRef.current.setView([Number(selected.latitude), Number(selected.longitude)], 14); }, [selected]);
  useEffect(() => { if (!route?.geometry || !mapRef.current) return; if (routeRef.current) mapRef.current.removeLayer(routeRef.current); routeRef.current = L.geoJSON(route.geometry, { style: { color: '#047857', weight: 6, opacity: .85 } }).addTo(mapRef.current); mapRef.current.fitBounds(routeRef.current.getBounds(), { padding: [24, 24] }); }, [route]);
  const locate = () => navigator.geolocation?.getCurrentPosition((position) => mapRef.current?.setView([position.coords.latitude, position.coords.longitude], 14), () => onToast('ไม่สามารถอ่านตำแหน่งได้'));
  const visibleCount = venues.filter((venue) => hasCoordinates(venue) && isMuslimRelated(venue) && (filter === 'all' || (filter === 'worship' ? venue.category === 'place_of_worship' : ['restaurant', 'cafe', 'fast_food'].includes(venue.category)))).length;
  const missingCount = venues.filter((venue) => !hasCoordinates(venue) && isMuslimRelated(venue)).length;
  return <section className={`${styles.root} screen active`}><header className="subheader"><button className="icon" onClick={onBack} aria-label="กลับ">‹</button><div><small>LIVE DISCOVERY</small><h1>แผนที่เชียงราย</h1></div><button className="icon" onClick={onLocate || locate} aria-label="ใช้ตำแหน่งปัจจุบัน">⌖</button></header><div className="map-intro"><div><b>แผนที่ร้านที่มีพิกัดยืนยัน</b><span>{visibleCount.toLocaleString('th-TH')} หมุด · อีก {missingCount.toLocaleString('th-TH')} ร้านค้นหาจากชื่อได้</span></div><button onClick={onLocate || locate}>ตำแหน่งของฉัน</button></div><div className="map-tools">{[['food', 'ร้านและคาเฟ่'], ['all', 'ทั้งหมด'], ['worship', 'มัสยิด']].map(([id, label]) => <button key={id} className={filter === id ? 'selected' : ''} onClick={() => setFilter(id)}>{label}</button>)}</div><div className="map-legend"><span><i className="legend-dot food-dot"></i>ร้าน/คาเฟ่</span><span><i className="legend-dot worship-dot"></i>มัสยิด</span><span><i className="legend-dot cluster-dot"></i>หลายรายการ</span></div><div ref={mapNode} id="map" />{missingCount > 0 && <div className="map-note"><b>ร้านที่ยังไม่มีหมุดในแอป</b><span>กดชื่อร้านจากหน้าแรกเพื่อเปิดตำแหน่งล่าสุดใน Google Maps ระบบจะไม่เดาพิกัดให้เอง</span><a href={mapsSearchUrl({ name: 'Halal restaurants Chiang Rai' })} target="_blank" rel="noreferrer">ค้นหาร้านฮาลาลใน Google Maps ↗</a></div>}<div className="route-panel"><b>{route?.summary || (selected ? `เลือก ${selected.name}` : 'แตะหมุดเพื่อดูรายละเอียด')}</b><span>{route ? 'เส้นทางแสดงอยู่บนแผนที่นี้' : 'สถานะฮาลาลต้องตรวจสอบกับร้านก่อนใช้บริการ'}</span></div></section>;
}
