import { useEffect, useRef, useState } from 'react';
import L from 'leaflet';
import 'leaflet.markercluster';
import { categoryName, favoriteIds } from '../../utils/storage.js';
import styles from './MapPage.module.css';

const center = [19.9072, 99.8309];
export default function MapPage({ venues, onBack, onLocate, onRoute, selected, onFavorite, onToast, route }) {
  const mapNode = useRef(null); const mapRef = useRef(null); const clusterRef = useRef(null); const routeRef = useRef(null); const [filter, setFilter] = useState('food');
  useEffect(() => { if (!mapNode.current || mapRef.current) return undefined; mapRef.current = L.map(mapNode.current, { preferCanvas: true }).setView(center, 10); L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png', { maxZoom: 20, subdomains: 'abcd', attribution: '© OpenStreetMap © CARTO' }).addTo(mapRef.current); return () => { mapRef.current?.remove(); mapRef.current = null; }; }, []);
  useEffect(() => { const map = mapRef.current; if (!map) return; if (clusterRef.current) map.removeLayer(clusterRef.current); const places = venues.filter((venue) => venue.latitude && venue.longitude).filter((venue) => filter === 'all' || (filter === 'worship' ? venue.category === 'place_of_worship' : ['restaurant', 'cafe', 'fast_food'].includes(venue.category))); const clusters = L.markerClusterGroup({ showCoverageOnHover: false, maxClusterRadius: 46, disableClusteringAtZoom: 15, spiderfyOnMaxZoom: true }); places.forEach((venue) => { const marker = L.marker([venue.latitude, venue.longitude], { title: venue.name || 'สถานที่' }); marker.bindPopup(`<b>${venue.name || 'สถานที่'}</b><br>${categoryName(venue)}<br><button class="map-route" data-route-id="${venue.id}">นำทางในแอพ</button><button class="map-favorite" data-map-fav="${venue.id}">${favoriteIds().includes(venue.id) ? '♥ บันทึกแล้ว' : '♡ บันทึก'}</button>`); marker.on('popupopen', () => { const route = document.querySelector(`[data-route-id="${venue.id}"]`); const favorite = document.querySelector(`[data-map-fav="${venue.id}"]`); route?.addEventListener('click', () => onRoute(venue)); favorite?.addEventListener('click', () => onFavorite(venue.id)); }); clusters.addLayer(marker); }); clusterRef.current = clusters.addTo(map); map.invalidateSize(); }, [venues, filter, onFavorite, onRoute]);
  useEffect(() => { if (!selected || !mapRef.current) return; mapRef.current.setView([selected.latitude, selected.longitude], 14); }, [selected]);
  useEffect(() => { if (!route?.geometry || !mapRef.current) return; if (routeRef.current) mapRef.current.removeLayer(routeRef.current); routeRef.current = L.geoJSON(route.geometry, { style: { color: '#047857', weight: 6, opacity: .85 } }).addTo(mapRef.current); mapRef.current.fitBounds(routeRef.current.getBounds(), { padding: [24, 24] }); }, [route]);
  const locate = () => navigator.geolocation?.getCurrentPosition((position) => mapRef.current?.setView([position.coords.latitude, position.coords.longitude], 14), () => onToast('ไม่สามารถอ่านตำแหน่งได้'));
  return <section className={`${styles.root} screen active`}><header className="subheader"><button className="icon" onClick={onBack}>‹</button><div><small>LIVE DISCOVERY</small><h1>แผนที่เชียงราย</h1></div><button className="icon" onClick={onLocate || locate}>⌖</button></header><div className="map-tools">{[['food', 'อาหาร'], ['all', 'ทั้งหมด'], ['worship', 'มัสยิด']].map(([id, label]) => <button key={id} className={filter === id ? 'selected' : ''} onClick={() => setFilter(id)}>{label}</button>)}</div><div className="map-legend"><span><i className="legend-dot food-dot"></i>อาหาร</span><span><i className="legend-dot worship-dot"></i>สถานที่ละหมาด</span><span><i className="legend-dot cluster-dot"></i>กลุ่มสถานที่</span></div><div ref={mapNode} id="map" /><div className="route-panel"><b>{route?.summary || (selected ? `เลือก ${selected.name}` : 'เลือกสถานที่บนแผนที่')}</b><span>{route ? `เส้นทางแสดงอยู่บนแผนที่ในแอพนี้` : 'เส้นทางจะแสดงในเว็บนี้ ไม่เปิดแอพอื่น'}</span></div></section>;
}